#Requires AutoHotkey v2.0
; Thin headless adapter for Task 7 diagnostic UI tests.
; Product methods live in DiagnosticUI.Product.ahk (generated by DiagnosticUI.Tests.ps1).
; This file must not reimplement reason/title/buttons/rotation/redaction logic.
#Include %A_ScriptDir%\DiagnosticUI.Product.ahk

cmd := A_Args.Length >= 1 ? A_Args[1] : ""
jsonPath := A_Args.Length >= 2 ? A_Args[2] : ""
outPath := A_Args.Length >= 3 ? A_Args[3] : "*"
caseKey := A_Args.Length >= 4 ? A_Args[4] : ""

jsonText := ""
if (jsonPath != "" && FileExist(jsonPath))
    jsonText := FileRead(jsonPath, "UTF-8")

try {
    resultJson := RunDiagnosticUICommand(cmd, jsonText, caseKey)
} catch as err {
    resultJson := '{"ok":false,"error":"' EscapeJson(err.Message) '"}'
}

if (outPath = "*" || outPath = "")
    FileAppend(resultJson "`n", "*", "UTF-8")
else {
    try FileDelete(outPath)
    FileAppend(resultJson, outPath, "UTF-8")
}
ExitApp(0)
